In [ ]:
%matplotlib inline


What is PyTorch?
================

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다:

-  NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
-  최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

Getting Started
---------------

Tensor는 NumPy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능합니다.



In [ ]:
from __future__ import print_function
import torch

torch.__version__

'1.12.1+cu113'

초기화되지 않은 5x3 행렬을 생성합니다:



In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[9.8230e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


무작위로 초기화된 행렬을 생성합니다:



In [ ]:
x = torch.randn(5, 3) # normal distribution sampling
print(x)
x = torch.rand(5, 3)  # 0~1 사이의 값 sampling
print(x)

tensor([[-1.3986, -0.2684,  0.0860],
        [-0.0455, -0.7864,  1.4580],
        [ 1.9342, -0.5584, -0.3059],
        [-0.9159, -0.4336, -0.4687],
        [-0.7757,  0.1979, -1.1054]])
tensor([[0.6255, 0.7690, 0.5224],
        [0.8808, 0.4944, 0.0941],
        [0.0503, 0.7888, 0.0443],
        [0.7185, 0.7746, 0.8149],
        [0.0607, 0.3531, 0.8362]])


dtype이 long이고 0으로 채워진 행렬을 생성합니다:



In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


데이터로부터 tensor를 직접 생성합니다:



In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


또는 존재하는 tensor를 바탕으로 tensor를 만듭니다. 
이 메소드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용합니다.


In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6824, -0.1961,  0.4658],
        [ 1.7975,  0.0205,  0.6170],
        [-0.8572,  0.2335,  1.1923],
        [ 0.6501,  1.6362, -0.2130],
        [ 1.3056, -1.0711, -0.9115]])


행렬의 크기를 구합니다:



In [ ]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])



덧셈: 문법1

In [ ]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[ 0.6824, -0.1961,  0.4658],
        [ 1.7975,  0.0205,  0.6170],
        [-0.8572,  0.2335,  1.1923],
        [ 0.6501,  1.6362, -0.2130],
        [ 1.3056, -1.0711, -0.9115]])
tensor([[0.5257, 0.3267, 0.4638],
        [0.8507, 0.8463, 0.6182],
        [0.9160, 0.7931, 0.2528],
        [0.8125, 0.3364, 0.5586],
        [0.6247, 0.7228, 0.7866]])
tensor([[ 1.2081,  0.1306,  0.9296],
        [ 2.6482,  0.8668,  1.2352],
        [ 0.0588,  1.0267,  1.4451],
        [ 1.4626,  1.9726,  0.3456],
        [ 1.9303, -0.3483, -0.1249]])


덧셈: 문법2



In [ ]:
print(torch.add(x, y))

tensor([[ 1.2081,  0.1306,  0.9296],
        [ 2.6482,  0.8668,  1.2352],
        [ 0.0588,  1.0267,  1.4451],
        [ 1.4626,  1.9726,  0.3456],
        [ 1.9303, -0.3483, -0.1249]])


덧셈: 결과 tensor를 인자로 제공


In [ ]:
result = torch.empty(5, 3)
print(result)

torch.add(x, y, out=result)
print(result)

tensor([[ 9.8235e-35,  0.0000e+00,  9.2962e-01],
        [ 2.6482e+00,  8.6682e-01,  1.2352e+00],
        [ 5.8791e-02,  1.0267e+00,  1.4451e+00],
        [ 1.4626e+00,  1.9726e+00,  3.4562e-01],
        [ 1.9303e+00, -3.4831e-01, -1.2490e-01]])
tensor([[ 1.2081,  0.1306,  0.9296],
        [ 2.6482,  0.8668,  1.2352],
        [ 0.0588,  1.0267,  1.4451],
        [ 1.4626,  1.9726,  0.3456],
        [ 1.9303, -0.3483, -0.1249]])


덧셈: 바꿔치기(In-place) 방식


In [ ]:
# adds x to y
print(y)
y.add_(x)
print(y)

tensor([[0.5257, 0.3267, 0.4638],
        [0.8507, 0.8463, 0.6182],
        [0.9160, 0.7931, 0.2528],
        [0.8125, 0.3364, 0.5586],
        [0.6247, 0.7228, 0.7866]])
tensor([[ 1.2081,  0.1306,  0.9296],
        [ 2.6482,  0.8668,  1.2352],
        [ 0.0588,  1.0267,  1.4451],
        [ 1.4626,  1.9726,  0.3456],
        [ 1.9303, -0.3483, -0.1249]])


<div class="alert alert-info"><h4>Note</h4><p>바꿔치기(In-place) 방식으로 tensor의 값을 변경하는 연산은 _ 를 접미사로 갖습니다.<p>
예: x.copy_(y), x.t_() 는 x 를 변경합니다.

<p>
NumPy스러운 인덱싱 표기 방법을 사용할 수도 있습니다!


In [ ]:
print(x)
print(x[:, 1])

tensor([[ 0.6824, -0.1961,  0.4658],
        [ 1.7975,  0.0205,  0.6170],
        [-0.8572,  0.2335,  1.1923],
        [ 0.6501,  1.6362, -0.2130],
        [ 1.3056, -1.0711, -0.9115]])
tensor([-0.1961,  0.0205,  0.2335,  1.6362, -1.0711])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view 를 사용합니다:


In [ ]:
x = torch.randn(4, 4)
print(x)

y = x.view(16)
z = y.view(-1, 2)  # the size -1 is inferred from other dimensions
print(y)
print(z)
print(y.size(), z.size())

tensor([[-0.0718,  0.7445, -0.5144, -1.2786],
        [ 1.5802,  0.1535,  0.5422, -1.0773],
        [ 0.5343,  0.0876, -0.3986, -0.7450],
        [-0.9419,  0.9376, -0.9235,  1.1597]])
tensor([-0.0718,  0.7445, -0.5144, -1.2786,  1.5802,  0.1535,  0.5422, -1.0773,
         0.5343,  0.0876, -0.3986, -0.7450, -0.9419,  0.9376, -0.9235,  1.1597])
tensor([[-0.0718,  0.7445],
        [-0.5144, -1.2786],
        [ 1.5802,  0.1535],
        [ 0.5422, -1.0773],
        [ 0.5343,  0.0876],
        [-0.3986, -0.7450],
        [-0.9419,  0.9376],
        [-0.9235,  1.1597]])
torch.Size([16]) torch.Size([8, 2])


만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있습니다.



In [ ]:
x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
print(x.item())


tensor([1.1668])
<class 'torch.Tensor'> <class 'float'>
1.1668429374694824


**읽을 거리:**


  전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 난수(random number) 등과 같은 100가지 이상의 Tensor 연산은
  `여기 <http://pytorch.org/docs/torch>` 에 설명되어 있습니다.

NumPy 변환(Bridge)
------------

Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

(CPU 상의) Torch Tensor와 NumPy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

- Torch Tensor를 NumPy 배열로 변환하기



In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


NumPy 배열의 값이 어떻게 변하는지 확인해보세요.



In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
temp = a.clone()
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


 - NumPy 배열을 Torch Tensor로 변환하기  
 
NumPy(np) 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보세요.



In [ ]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로의 변환을 지원하며, (NumPy에서 Tensor로의) 반대 변환도 지원합니다.

CUDA Tensors
------------

.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.



In [ ]:
import torch

# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.

x = torch.rand(4,4)
if torch.cuda.is_available():
    device = "cuda:0" # torch.device("cuda:0")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    print(y)


    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1.2081, 1.4497, 1.2873, 1.2779],
        [1.1535, 1.5532, 1.2098, 1.8122],
        [1.1709, 1.8269, 1.4140, 1.9999],
        [1.6878, 1.2743, 1.8011, 1.2985]], device='cuda:0')
tensor([[1.2081, 1.4497, 1.2873, 1.2779],
        [1.1535, 1.5532, 1.2098, 1.8122],
        [1.1709, 1.8269, 1.4140, 1.9999],
        [1.6878, 1.2743, 1.8011, 1.2985]], dtype=torch.float64)


In [ ]:
x = x.cuda()