https://www.tensorflow.org/guide/tensor

In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.2


##변수 생성

In [2]:
#모양이 [1, 2, 3]이고 값은 0으로 채워진 3차원 텐서가 변수로 생성
my_variable = tf.Variable(tf.zeros([1, 2, 3]))
my_variable

<tf.Variable 'Variable:0' shape=(1, 2, 3) dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

##변수의 사용

In [3]:
# 텐서플로 그래프에서 tf.Variable의 값을 사용하려면 이를 단순히 tf.Tensor로 취급하면 됨
v = tf.Variable(0.0)
print(v)
w = v + 1  # w는 v값 기준으로 계산되는 tf.Tensor 입니다.
           # 변수가 수식에 사용될 때, 변수는 자동적으로
           # tf.Tensor로 변환되어 값을 표현합니다.
print(w)
        

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>
tf.Tensor(1.0, shape=(), dtype=float32)


In [4]:
#값을 변수에 할당하려면 assign, assign_add 메소드와 tf.Variable 클래스에 있는 친구들(friends)을 사용
a = tf.Variable(0.0)
a.assign_add(1)
a.read_value()  # 1.0

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

##tf.Tensor 객체의 랭크는 그 차원의 수

## 랭크 0

In [5]:
mammal = tf.Variable("코끼리", tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.14159265359, tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)

print(mammal)
print(ignition)
print(floating)
print(its_complicated)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'\xec\xbd\x94\xeb\x81\xbc\xeb\xa6\xac'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=451>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.1415927>
<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(12.3-4.85j)>


## 랭크 1 (벡터)

In [6]:
mystr = tf.Variable(["안녕하세요"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

print(mystr)
print(cool_numbers)
print(first_primes)
print(its_very_complicated)
tf.rank(mystr)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=
array([b'\xec\x95\x88\xeb\x85\x95\xed\x95\x98\xec\x84\xb8\xec\x9a\x94'],
      dtype=object)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3.14159, 2.71828], dtype=float32)>
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2,  3,  5,  7, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([12.3-4.85j,  7.5-6.23j])>


<tf.Tensor: shape=(), dtype=int32, numpy=1>

## 고차원 랭크(랭크2, 랭크 2 tf.Tensor 객체는 최소 한 개 이상의 열과 행으로 구성됩니다)

In [7]:
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False, True],[True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([ [4, 9], [16, 25] ], tf.int32)

#tf.rank : 객체의 랭크 구하기 
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7],[11]], tf.int32)

print(mymat)
print(rank_of_squares)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[ 7],
       [11]], dtype=int32)>
tf.Tensor(2, shape=(), dtype=int32)


In [8]:
my_image = tf.zeros([10, 299, 299, 3])  # 배치 x 높이 x 너비 x 색상

# H*W = 299 * 299

## tf.Tensor 객체 랭크 구하기

In [9]:
r = tf.rank(my_image)
print(r)
# 이 코드가 실행된 후 r은 4라는 값을 가지게 됩니다.

tf.Tensor(4, shape=(), dtype=int32)


## tf.Tensor 원소 참조하기

In [10]:
my_vector = tf.Variable([1, 2, 3, 4], tf.int32)
print(tf.rank(my_vector))

my_scalar = my_vector[2]
print(my_scalar)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [11]:
print(squarish_squares)
my_scalar = squarish_squares[1, 0] # 2행 1열의 값 
print(my_scalar) 

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  9],
       [16, 25]], dtype=int32)>
tf.Tensor(16, shape=(), dtype=int32)


In [12]:
my_row_vector = squarish_squares[1]
my_column_vector = squarish_squares[:, 1]
print(squarish_squares)
print(my_row_vector)
print(my_column_vector)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  9],
       [16, 25]], dtype=int32)>
tf.Tensor([16 25], shape=(2,), dtype=int32)
tf.Tensor([ 9 25], shape=(2,), dtype=int32)


## tf.Tensor 객체 형태 얻기

In [13]:
zeros = tf.zeros(squarish_squares.shape) # squarish_squares.shape으로 새로운 텐서 생성 
zeros

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

## tf.Tensor 형태 변경

In [14]:
#60
rank_three_tensor = tf.ones([3, 4, 5])
print(rank_three_tensor.shape)
print(rank_three_tensor)
matrix = tf.reshape(rank_three_tensor, [6, 10])  # 기존 내용을 6x10 행렬로
                                                 # 형태 변경
print('====matrix=====')                                   
print(matrix)
print(matrix.shape)

matrixB = tf.reshape(matrix, [3, -1])  # 기존 내용을 3x20 행렬로 형태 변경
                                       # -1은 차원 크기를 계산하여
                                       # 자동으로 결정하라는 의미
print('====matrixB=====') 
print(matrixB)
print(matrixB.shape)

matrixAlt = tf.reshape(matrixB, [4, 3, -1])  # 기존 내용을 4x3x5 텐서로
                                             # 형태 변경
print(matrixAlt.shape)

# 형태가 변경된 텐서의 원소 개수는
# 원래 텐서의 원소 개수와 같습니다.
# 그러므로 다음은 원소 개수를 유지하면서
# 마지막 차원에 사용 가능한 수가 없기 때문에 에러를 발생합니다.
yet_another = tf.reshape(matrixAlt, [13, 2, -1])  # 에러!

(3, 4, 5)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 4, 5), dtype=float32)
====matrix=====
tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(6, 10), dtype=float32)
(6, 10)
====matrixB=====
tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(3, 20), dtype=float32)
(3, 20)
(4, 3, 5)


InvalidArgumentError: ignored

## 자료형

In [15]:
# 정수형 텐서를 실수형으로 변환.
a=tf.constant([1,2,3])
print(a)

float_tensor = tf.cast(tf.constant([1, 2, 3]), dtype=tf.float32)
float_tensor

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>