# 인공지능 수학 - 선형대수 (NumPy 실습)
## 행렬과 벡터의 코딩 및 연산

In [1]:
import numpy as np

In [2]:
# 행렬 코딩
A = np.array([[3, 1, 1], [1, -2, -1], [1, 1, 1]])

print(A)
print(np.shape(A))

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


In [3]:
# 벡터 코딩
b = np.array([4, 1, 2])

print(b)
print(np.shape(b))

[4 1 2]
(3,)


In [4]:
# 역행렬 구하기
A_inv = np.linalg.inv(A)  

print(A_inv)
print(np.shape(A_inv))

[[ 5.00000000e-01 -7.40148683e-17 -5.00000000e-01]
 [ 1.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [-1.50000000e+00  1.00000000e+00  3.50000000e+00]]
(3, 3)


In [5]:
# 역행렬을 이용한 선형시스템 Ax=b의 해 구하기
# x = np.matmul(A_inv, b)
x = A_inv @ b

print(x)
print(np.shape(x))

[ 1. -1.  2.]
(3,)


In [6]:
## 결과 검증
# bb = np.matmul(A, x)
bb = A @ x

print(np.shape(bb))
print(bb)

if np.linalg.norm(b - bb) < 1e-3:
    print("Ok")
else:
    print("something wrong")

(3,)
[4. 1. 2.]
Ok
